#!/bin/sh
set -x

MY_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CACHE_PATH=$MY_PATH/../../.cache
BIN_PATH=$MY_PATH/../../bin/

mkdir -p $CACHE_PATH

mongoVersion="2.6.6"
mongoPlatform="osx"
mongoPlatformArch="x86_64"
mongoFile="mongodb-${mongoPlatform}-${mongoPlatformArch}-${mongoVersion}"

src="http://fastdl.mongodb.org/${mongoPlatform}/${mongoFile}.tgz";
dest=$CACHE_PATH/${mongoFile}.tgz

curl -C - $src -O $dest -z $dest

tar -zxvf $CACHE_PATH/${mongoFile}.tgz -C $MY_PATH

mkdir -p $MY_PATH/data

ln -fs $MY_PATH/${mongoFile} $MY_PATH/mongo
ln -fs $MY_PATH/mongo/bin/mongo $BIN_PATH
